# Generated by Django 5.2.6 on 2025-09-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tweet",
        ),
    ]
