# Generated by Django 5.2.6 on 2025-09-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="likeCount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tweet",
            name="liked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.URLField(
                blank=True,
                default="https://api.dicebear.com/7.x/bottts/png?size=40",
                max_length=500,
                null=True,
            ),
        ),
    ]
