# Generated by Django 5.2.6 on 2025-09-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_followers_profile_following_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
